### ISSUE TITLE
My balls itch

### ISSUE THREAD

**Issue by AidanCorgi4556** [LinusUsernameTips/troll-1gb#1]
My balls are itchy
![image](https://user-images.githubusercontent.com/83181250/132988158-721c7920-bfeb-46c7-b9c7-2e36ad37bc98.png)

**Comment by f7cjo** [comment]
take a bath stinky

**Comment by AidanCorgi4556** [comment]
I did (:

**Comment by AidanCorgi4556** [comment]
You will die soon

**Comment by f7cjo** [comment]
not if you die first

**Comment by LinusUsernameTips** [comment]
Soloution : itch your balls

**Comment by AidanCorgi4556** [comment]
You mean scratch?

**Comment by LinusUsernameTips** [comment]
no
